# Generated by Django 5.1 on 2024-08-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="temp_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
