# Generated by Django 5.1 on 2024-08-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
    ]
