name: Radiance Test&Linters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Apply migrations
        env:
          DATABASE_URL: postgres://myuser:mypassword@localhost:5432/mydb
          DJANGO_SECRET_KEY: some_secret_key
        run: |
          poetry run python manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: postgres://myuser:mypassword@localhost:5432/mydb
          DJANGO_SECRET_KEY: some_secret_key
        run: |
          poetry run python manage.py test

  black:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only dev --no-root

    - name: Run black
      run: poetry run black --diff --check .

  isort:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only dev --no-root

    - name: Run isort
      run: poetry run isort --check-only --diff --profile black .

  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only dev --no-root

    - name: Run flake8
      run: poetry run flake8 .
